name: run tests

on: [push]

jobs:
  run_tests:
    runs-on: macos-11
    steps:
      - name: Pwd
        run: pwd
      - name: Delete
        run: rm moldgag/moldgag.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
#     - uses: swift-actions/setup-swift@v1
#       with:
#         swift-version: "5.6.1"
#     - name: Get swift version
#       run: swift --version # Swift 5.6.1
#     - uses: actions/checkout@v1
#     - name: Select Xcode
#       run: sudo xcode-select -switch /Applications/Xcode_13.0.app && /usr/bin/xcodebuild -version
#     - name: Run tests
#       run: xcodebuild test -scheme moldgag -project moldgag.xcodeproj -clonedSourcePackagesDirPath SourcePackages -destination 'platform=iOS Simulator,name=iPhone 12,OS=15.0' | xcpretty && exit ${PIPESTATUS[0]}
